image: comp1531/automarking:latest

stages:
  - checks

before_script:
  - npm install

tests:
  stage: checks
  only:
    - master
    - merge_requests
  script:
    - SERVER_LOG=$(mktemp)
    # Start server
    - npm run start >& $SERVER_LOG &
    - timeout 10s grep -q "⚡️ Server started on port" <(tail -f $SERVER_LOG) || (cat $SERVER_LOG && exit 1)
    # Run test and kill server
    - timeout -s SIGINT 180s npm run test || (cat $SERVER_LOG && exit 1)
    - kill -SIGINT %1
    - sleep 2
    - cat $SERVER_LOG

typescript:
  stage: checks
  script:
    - npm run tsc

linting:
  stage: checks
  script:
    - npm run lint